spring.application.name=api-gateway

server.port=8080

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# Gateway routes - IAM Auth
spring.cloud.gateway.server.webmvc.routes[0].id=iam-auth-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://iam-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

# Gateway routes - IAM Users
spring.cloud.gateway.server.webmvc.routes[1].id=iam-users-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://iam-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/**

# [DEV.] Gateway routes - Conference Service
# spring.cloud.gateway.server.webmvc.routes[2].id=conference-service-route
# spring.cloud.gateway.server.webmvc.routes[2].uri=lb://conference-service
# spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/congresses/**,/api/v1/conferences/**

# [PEND.] Gateway - Wallet Service
# spring.cloud.gateway.server.webmvc.routes[3].id=wallet-service-route
# spring.cloud.gateway.server.webmvc.routes[3].uri=lb://wallet-service
# spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/wallet/**,/api/v1/payments/**